### ISSUE TITLE
Add Update Directory Patching

### ISSUE THREAD

**Issue by playerjmr** [Lekoopapaul/sdcafiineplus_plugin#1]
Hello, I was trying to give myself custom skin packs in Minecraft: Wii U Edition using the original repository of the SDCafiine Plugin, but it seems that support for patching in the update directory, 0005000e, was never implemented. This is where Minecraft DLC skins were stored. I was wondering if this is a feature you might be willing to implement in your fork of the SDCafiine Plugin, SDCafiinePlus?

**Comment by Lekoopapaul** [comment]
The Update files are under:
root:/wiiu/sdcafiine_plus/[TITLEID from Game]/[MODPACK]/content/

The Update and Game files are handled the same

**Comment by playerjmr** [comment]
> The Update files are under: root:/wiiu/sdcafiine_plus/[TITLEID from Game]/[MODPACK]/content/
> 
> The Update and Game files are handled the same

Was this changed from the original? because on the original it was not working at all. i havent tried it on sdcafiine plus yet

**Comment by Lekoopapaul** [comment]
I tried it myself and it worked. You must put the .pck file under:

root:/wiiu/sdcafiine_plus/[TITLEID]/[MODPACK]/content/WiiU/DLC/[Skin Pack Name]/

TITLEID for minecraft on Wiiu is:
Europe: 00050000101d7500
USA: 00050000101d9d00
Japan: 00050000101dbe00

I have attached a example Modpack.
[test.zip](https://github.com/user-attachments/files/17777135/test.zip)

Skin pack is from [https://gamebanana.com/mods/534259](https://gamebanana.com/mods/534259)

**Comment by Lekoopapaul** [comment]
It should also work in the original
